<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classement Bundesliga</title>
    <link rel="stylesheet" href="/front/css/style.css">
</head>
<body>
    <header>
        <div class="Nom">
            <img id="logo" src="/front/img/Logo.png" alt="Logo">
            <h3>Europe Football Classement</h3>
        </div>
        <a href="index.html" class="nav">ACCUEIL</a>
        <a href="index.html" class="nav">CLASSEMENT</a>
        <a href="index.html" class="nav">MAP</a>
        <div class="boutton">
            <button id="inscription"><a href="/front/inscription_connexion/inscription.html">INSCRIPTION</a></button>
            <button id="connexion"><a href="/front/inscription_connexion/connexion.html">CONNEXION</a></button>
        </div>
    </header>

<section class="categories-wrapper section-padding3">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                
                <div class="tc-widget-standings-style8">
                    <h3 class="tc-widget-title mb-30">Classement Bundesliga</h3>
                    <form action="contact.php" class="form">
                        
                    </form>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Position</th>
                                    <th>Club</th>
                                    <th>Points</th>
                                    <th>Joués</th>
                                    <th>Gagnés</th>
                                    <th>Nuls</th>
                                    <th>Perdus</th>
                                    <th>Buts Pour</th>
                                    <th>Buts Contre</th>
                                    <th>DIFF.</th>
                                    <th>Forme</th>
                                </tr>
                            </thead>
                            
                                <tr>
                                    <td>1</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/Bayer-04-Leverkusen-Logo.png" alt="leverkusen"></div>
                                        <div class="team-details">
                                            <div class="team-name">BAYER LEVERKUSEN</div>
                                        </div>
                                    </td>
                                    <td>31</td>
                                    <td>11</td>
                                    <td>10</td>
                                    <td>1</td>
                                    <td>0</td>
                                    <td>34</td>
                                    <td>10</td>
                                    <td>+24</td>
                                    <td class="form">
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/Logo_FC_Bayern_München_(2002–2017).svg.png" alt="bayern"></div>
                                        <div class="team-details">
                                            <div class="team-name">BAYERN MUNICH</div>
                                        </div>
                                    </td>
                                    <td>29</td>
                                    <td>11</td>
                                    <td>9</td>
                                    <td>2</td>
                                    <td>0</td>
                                    <td>42</td>
                                    <td>9</td>
                                    <td>+33</td>
                                    <td class="form">
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/stuttgart.png" alt="stuttgart"></div>
                                        <div class="team-details">
                                            <div class="team-name">VFB STUTTGART</div>
                                        </div>
                                    </td>
                                    <td>24</td>
                                    <td>11</td>
                                    <td>8</td>
                                    <td>0</td>
                                    <td>3</td>
                                    <td>29</td>
                                    <td>14</td>
                                    <td>+15</td>
                                    <td class="form">
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round red"></span>
                                        <span class="round red"></span>
                                        <span class="round green"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/RB_Leipzig_2014_logo.svg.png" alt="leipzig"></div>
                                        <div class="team-details">
                                            <div class="team-name">RB LEIPZIG</div>
                                        </div>
                                    </td>
                                    <td>23</td>
                                    <td>11</td>
                                    <td>7</td>
                                    <td>2</td>
                                    <td>2</td>
                                    <td>28</td>
                                    <td>10</td>
                                    <td>+18</td>
                                     <td class="form">
                                        <span class="round gray"></span>
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round red"></span>
                                        <span class="round green"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/Borussia_Dortmund_logo.svg.png" alt="dortmund"></div>
                                        <div class="team-details">
                                            <div class="team-name">BORUSSIA DORTMUND</div>
                                        </div>
                                    </td>
                                    <td>21</td>
                                    <td>11</td>
                                    <td>6</td>
                                    <td>3</td>
                                    <td>2</td>
                                    <td>21</td>
                                    <td>17</td>
                                    <td>+4</td>
                                     <td class="form">
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round gray"></span>
                                        <span class="round red"></span>
                                        <span class="round red"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>6</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/Hoffenheim.png" alt="hoffeinheim"></div>
                                        <div class="team-details">
                                            <div class="team-name">HOFFENHEIM</div>
                                        </div>
                                    </td>
                                    <td>19</td>
                                    <td>11</td>
                                    <td>6</td>
                                    <td>1</td>
                                    <td>4</td>
                                    <td>23</td>
                                    <td>20</td>
                                    <td>+3</td>
                                    <td class="form">
                                        <span class="round red"></span>
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round red"></span>
                                        <span class="round gray"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>7</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/francfort.png" alt="francfort"></div>
                                        <div class="team-details">
                                            <div class="team-name">EINTRACHT FRANCFORT</div>
                                        </div>
                                    </td>
                                    <td>18</td>
                                    <td>11</td>
                                    <td>4</td>
                                    <td>6</td>
                                    <td>1</td>
                                    <td>17</td>
                                    <td>11</td>
                                    <td>+6</td>
                                    <td class="form">
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round gray"></span>
                                        <span class="round green"></span>
                                        <span class="round gray"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>8</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/fribourg.png" alt="fribourg"></div>
                                        <div class="team-details">
                                            <div class="team-name">FRIBOURG</div>
                                        </div>
                                    </td>
                                    <td>14</td>
                                    <td>11</td>
                                    <td>4</td>
                                    <td>2</td>
                                    <td>5</td>
                                    <td>14</td>
                                    <td>22</td>
                                    <td>-8</td>
                                     <td class="form">
                                        <span class="round red"></span>
                                        <span class="round green"></span>
                                        <span class="round red"></span>
                                        <span class="round gray"></span>
                                        <span class="round red"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>9</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/gladbach.png" alt="gladbach"></div>
                                        <div class="team-details">
                                            <div class="team-name">BORUSSIA M'GLADBACH</div>
                                        </div>
                                    </td>
                                    <td>12</td>
                                    <td>11</td>
                                    <td>3</td>
                                    <td>4</td>
                                    <td>4</td>
                                    <td>23</td>
                                    <td>23</td>
                                    <td>0</td>
                                     <td class="form">
                                        <span class="round gray"></span>
                                        <span class="round red"></span>
                                        <span class="round green"></span>
                                        <span class="round gray"></span>
                                        <span class="round green"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>10</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/augsburg.png" alt="augsburg"></div>
                                        <div class="team-details">
                                            <div class="team-name">AUGSBURG</div>
                                        </div>
                                    </td>
                                    <td>13</td>
                                    <td>11</td>
                                    <td>3</td>
                                    <td>4</td>
                                    <td>4</td>
                                    <td>20</td>
                                    <td>23</td>
                                    <td>-3</td>
                                    <td class="form">
                                        <span class="round red"></span>
                                        <span class="round green"></span>
                                        <span class="round green"></span>
                                        <span class="round gray"></span>
                                        <span class="round gray"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>11</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/wolfsburg.png" alt="wolfsburg"></div>
                                        <div class="team-details">
                                            <div class="team-name">WOLFSBURG</div>
                                        </div>
                                    </td>
                                    <td>13</td>
                                    <td>11</td>
                                    <td>4</td>
                                    <td>1</td>
                                    <td>6</td>
                                    <td>15</td>
                                    <td>20</td>
                                    <td>-5</td>
                                    <td class="form">
                                        <span class="round red"></span>
                                        <span class="round red"></span>
                                        <span class="round red"></span>
                                        <span class="round gray"></span>
                                        <span class="round red"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>12</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/werder.png" alt="werder"></div>
                                        <div class="team-details">
                                            <div class="team-name">WERDER BREME</div>
                                        </div>
                                    </td>
                                    <td>11</td>
                                    <td>11</td>
                                    <td>3</td>
                                    <td>2</td>
                                    <td>6</td>
                                    <td>18</td>
                                    <td>22</td>
                                    <td>-4</td>
                                    <td class="form">
                                        <span class="round red"></span>
                                        <span class="round red"></span>
                                        <span class="round green"></span>
                                        <span class="round gray"></span>
                                        <span class="round gray"></span>
                                </td>
                                </tr>
                                
                                <tr>
                                    <td>13</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/heideheim.png" alt="heindeheim"></div>
                                        <div class="team-details">
                                            <div class="team-name">HEIDENHEIM</div>
                                        </div>
                                    </td>
                                    <td>10</td>
                                    <td>11</td>
                                    <td>3</td>
                                    <td>1</td>
                                    <td>7</td>
                                    <td>17</td>
                                    <td>26</td>
                                    <td>-9</td>
                                     <td class="form">
                                        <span class="round red"></span>
                                        <span class="round red"></span>
                                        <span class="round red"></span>
                                        <span class="round green"></span>
                                        <span class="round red"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>14</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/bochum.png" alt="bochum"></div>
                                        <div class="team-details">
                                            <div class="team-name">BOCHUM</div>
                                        </div>
                                    </td>
                                    <td>9</td>
                                    <td>11</td>
                                    <td>1</td>
                                    <td>6</td>
                                    <td>4</td>
                                    <td>11</td>
                                    <td>25</td>
                                    <td>-14</td>
                                    <td class="form">
                                        <span class="round gray"></span>
                                        <span class="round red"></span>
                                        <span class="round gray"></span>
                                        <span class="round green"></span>
                                        <span class="round gray"></span>
                                </td>
                                </tr>
                                <tr>
                                    <td>15</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/darmstadt.png" alt="darmstadt"></div>
                                        <div class="team-details">
                                            <div class="team-name">DARMSTADT</div>
                                        </div>
                                    </td>
                                    <td>8</td>
                                    <td>11</td>
                                    <td>2</td>
                                    <td>2</td>
                                    <td>7</td>
                                    <td>14</td>
                                    <td>32</td>
                                    <td>-18</td>
                                    <td class="form">
                                        <span class="round green"></span>
                                        <span class="round red"></span>
                                        <span class="round red"></span>
                                        <span class="round red"></span>
                                        <span class="round gray"></span>
                                </td>
                                </tr>
                                <tr class="light-gray-row">
                                    <td>16</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/mayence.png" alt="mayence"></div>
                                        <div class="team-details">
                                            <div class="team-name">MAYENCE</div>
                                        </div>
                                    </td>
                                    <td>7</td>
                                    <td>11</td>
                                    <td>1</td>
                                    <td>4</td>
                                    <td>6</td>
                                    <td>11</td>
                                    <td>24</td>
                                    <td>-13</td>
                                    <td class="form">
                                        <span class="round gray"></span>
                                        <span class="round red"></span>
                                        <span class="round gray"></span>
                                        <span class="round green"></span>
                                        <span class="round gray"></span>
                                </td>
                                </tr>
                                <tr class="dark-gray-row">
                                    <td>17</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/cologne.svg" alt="cologne"></div>
                                        <div class="team-details">
                                            <div class="team-name">FC COLOGNE</div>
                                        </div>
                                    </td>
                                    <td>6</td>
                                    <td>11</td>
                                    <td>1</td>
                                    <td>3</td>
                                    <td>7</td>
                                    <td>9</td>
                                    <td>23</td>
                                    <td>-14</td>
                                    <td class="form">
                                        <span class="round red"></span>
                                        <span class="round green"></span>
                                        <span class="round red"></span>
                                        <span class="round gray"></span>
                                        <span class="round gray"></span>
                                    
                                </tr>
                                
                                <tr class="dark-gray-row">
                                    <td>18</td>
                                    <td class="team">
                                        <div class="logo"><img src="/front/img/bundesliga/union_berlin.png" alt="union_berlin"></div>
                                        <div class="team-details">
                                            <div class="team-name">UNION BERLIN</div>
                                        </div>
                                    </td>
                                    
                                        <td>6</td>
                                        <td>11</td>
                                        <td>2</td>
                                        <td>0</td>
                                        <td>9</td>
                                        <td>11</td>
                                        <td>26</td>
                                        <td>-15</td>
                                        <td class="form">
                                            <span class="round red"></span>
                                            <span class="round red"></span>
                                            <span class="round red"></span>
                                            <span class="round red"></span>
                                            <span class="round red"></span>
                                    </td>
                                   
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                        </section>
                            </body>
                            <footer>
                                <div class="center">
                                <h1>E.F.C</h1>
                                <h3>Europe Football Classement</h3>
                                <p>&copy; 2023 E.F.C Europe Football Classement. Tous droits réservés.</p>
                                </div>
                            </footer>
                            
                               </html>